### ISSUE TITLE
Typing enter doesn't create a line break bellow but above

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#452]
## Bug Report

**Problematic behavior**
Today with Sophie she experiences a weird bug (see video bellow) when typing the enter key at the end of a bullet list.

**Expected behavior/code**
The line break should be created bellow.

**Steps to Reproduce**

**Environment**
- Impress version: Prod
- Platform: Chrome on MacOS

**Additional context
[Capture vidéo du 25-11-2024 19:33:39.webm](https://github.com/user-attachments/assets/1b28068b-47d8-4783-b0ac-9dab55641163)
Screenshots**

**Comment by virgile-dev** [comment]
Here is the console log
```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.Comprendre cette erreurAI
83-618d41b69ad13406.js:4 Caught error while handling a Yjs update RangeError: Position 9 out of range
at y.resolve (83-618d41b69ad13406.js:7:59109)
at y.resolveCached (83-618d41b69ad13406.js:7:59476)
at C.resolve (83-618d41b69ad13406.js:7:63003)
at u.create (83-618d41b69ad13406.js:7:97055)
at M (83-618d41b69ad13406.js:4:145876)
at 83-618d41b69ad13406.js:4:149641
at A.mux (83-618d41b69ad13406.js:4:143379)
at A._typeChanged (83-618d41b69ad13406.js:4:149246)
at Object.i (83-618d41b69ad13406.js:7:27082)
at tu (91bbf309-ee09c1fae8566f23.js:1:14192)
(anonyme) @ 83-618d41b69ad13406.js:4Comprendre cette erreurAI
83-618d41b69ad13406.js:7 TextSelection endpoint not pointing into a node with inline content (blockContainer)
c @ 83-618d41b69ad13406.js:7Comprendre cet avertissementAI
0713ebb2-4e96-42a7-9668-aa67f0475a16/:1

1
   Failed to load resource: the server responded with a status of 404 ()Comprendre cette erreurAI
ac81a989-98a8-43c4-8bc7-e3e996b3900d/:1 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: button
Ancestor with aria-hidden: <div id=​"__next">​…​​Comprendre cette erreurAI
483-618d41b69ad13406.js:7 Uncaught RangeError: Position -1 out of range
at y.resolve (83-618d41b69ad13406.js:7:59109)
at y.resolveCached (83-618d41b69ad13406.js:7:59476)
at C.resolve (83-618d41b69ad13406.js:7:63003)
at new e4 (b155a556-1f31affbf0c3add2.js:1:46994)
at b155a556-1f31affbf0c3add2.js:1:45983
at HTMLDivElement.<anonymous> (b155a556-1f31affbf0c3add2.js:1:79837)Comprendre cette erreurAI
583-618d41b69ad13406.js:7 Uncaught RangeError: Position -1 out of range
at y.resolve (83-618d41b69ad13406.js:7:59109)
at y.resolveCached (83-618d41b69ad13406.js:7:59476)
at C.resolve (83-618d41b69ad13406.js:7:63003)
at new e4 (b155a556-1f31affbf0c3add2.js:1:46994)
at b155a556-1f31affbf0c3add2.js:1:45983
at HTMLDivElement.<anonymous> (b155a556-1f31affbf0c3add2.js:1:79837)
resolve @ 83-618d41b69ad13406.js:7
resolveCached @ 83-618d41b69ad13406.js:7
resolve @ 83-618d41b69ad13406.js:7
e4 @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1Comprendre cette erreurAI
83-618d41b69ad13406.js:7 Uncaught TransformError: Cannot join blockGroup onto blockContainer
at new e (83-618d41b69ad13406.js:7:154966)
at b.step (83-618d41b69ad13406.js:7:155304)
at 83-618d41b69ad13406.js:7:161638
at b.split (83-618d41b69ad13406.js:7:161684)
at de2d1abe-9afceffc36ba3ee9.js:5:17746
at b779bb5e-315a65c3b8b8b215.js:1:28318
at Object.command (b779bb5e-315a65c3b8b8b215.js:1:1993)
at de2d1abe-9afceffc36ba3ee9.js:7:39525
at b779bb5e-315a65c3b8b8b215.js:1:28318
at Object.command (b779bb5e-315a65c3b8b8b215.js:1:2655)
e @ 83-618d41b69ad13406.js:7
step @ 83-618d41b69ad13406.js:7
(anonyme) @ 83-618d41b69ad13406.js:7
split @ 83-618d41b69ad13406.js:7
(anonyme) @ de2d1abe-9afceffc36ba3ee9.js:5
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ de2d1abe-9afceffc36ba3ee9.js:7
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ de2d1abe-9afceffc36ba3ee9.js:7
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
Enter @ de2d1abe-9afceffc36ba3ee9.js:7
(anonyme) @ b779bb5e-315a65c3b8b8b215.js:1
(anonyme) @ 83-618d41b69ad13406.js:7
(anonyme) @ b155a556-1f31affbf0c3add2.js:1
someProp @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1Comprendre cette erreurAI
383-618d41b69ad13406.js:7 Uncaught RangeError: Position -1 out of range
at y.resolve (83-618d41b69ad13406.js:7:59109)
at y.resolveCached (83-618d41b69ad13406.js:7:59476)
at C.resolve (83-618d41b69ad13406.js:7:63003)
at new e4 (b155a556-1f31affbf0c3add2.js:1:46994)
at b155a556-1f31affbf0c3add2.js:1:45983
at HTMLDivElement.<anonymous> (b155a556-1f31affbf0c3add2.js:1:79837)
resolve @ 83-618d41b69ad13406.js:7
resolveCached @ 83-618d41b69ad13406.js:7
resolve @ 83-618d41b69ad13406.js:7
e4 @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1
(anonyme) @ b155a556-1f31affbf0c3add2.js:1Comprendre cette erreurAI
683-618d41b69ad13406.js:7 Uncaught RangeError: Position -1 out of range
at y.resolve (83-618d41b69ad13406.js:7:59109)
at y.resolveCached (83-618d41b69ad13406.js:7:59476)
at C.resolve (83-618d41b69ad13406.js:7:63003)
at new e4 (b155a556-1f31affbf0c3add2.js:1:46994)
at b155a556-1f31affbf0c3add2.js:1:45983
at HTMLDivElement.<anonymous> (b155a556-1f31affbf0c3add2.js:1:79837)
```

**Comment by virgile-dev** [comment]
Fixed since Blocknotejs update
